"""Normalize triples and build the NetworkX knowledge graph."""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

import networkx as nx

from src.config import COST_REPORT_PATH, NORMALIZED_TRIPLES_PATH, TRIPLES_PATH


@dataclass(frozen=True)
class NormalizedTriple:
    """A cleaned triple ready to become a graph edge."""

    subject: str
    relation: str
    object: str
    source_chunk_id: str
    confidence: float


ENTITY_ALIASES = {
    "Google LLC": "Google",
    "Meta Platforms": "Meta",
    "AWS": "Amazon Web Services",
    "Amazon Web Services (AWS)": "Amazon Web Services",
    "Microsoft Azure": "Azure",
    "OpenAI LP": "OpenAI",
    "Nvidia": "NVIDIA",
}

CANONICAL_PRODUCTS = {
    "Azure",
    "Windows",
    "Microsoft Office",
    "GitHub",
    "LinkedIn",
    "Google Search",
    "Gmail",
    "Android",
    "Google Cloud",
    "AlphaGo",
    "AlphaFold",
    "Instagram",
    "WhatsApp",
    "iPhone",
    "iPad",
    "Mac",
    "Apple Vision Pro",
    "Beats Electronics",
    "Claude",
    "Amazon Web Services",
    "Twitch",
    "Whole Foods Market",
    "CUDA",
    "Model S",
    "Model 3",
    "Model X",
    "Model Y",
    "ChatGPT",
    "GPT-4",
}

CANONICAL_COMPANIES = {
    "OpenAI",
    "Microsoft",
    "Google",
    "Alphabet",
    "DeepMind",
    "Meta",
    "Apple",
    "Anthropic",
    "Amazon",
    "NVIDIA",
    "Tesla",
}

CANONICAL_PEOPLE = {
    "Sam Altman",
    "Greg Brockman",
    "Ilya Sutskever",
    "John Schulman",
    "Wojciech Zaremba",
    "Elon Musk",
    "Bill Gates",
    "Paul Allen",
    "Larry Page",
    "Sergey Brin",
    "Mark Zuckerberg",
    "Eduardo Saverin",
    "Andrew McCollum",
    "Dustin Moskovitz",
    "Chris Hughes",
    "Steve Jobs",
    "Steve Wozniak",
    "Ronald Wayne",
    "Dario Amodei",
    "Daniela Amodei",
    "Jeff Bezos",
    "Jensen Huang",
    "Chris Malachowsky",
    "Curtis Priem",
    "Martin Eberhard",
    "Marc Tarpenning",
}


def canonicalize_entity(name: str) -> str:
    """Normalize whitespace and map common aliases to canonical names."""

    clean_name = " ".join(str(name).strip().split())
    return ENTITY_ALIASES.get(clean_name, clean_name)


def canonicalize_relation(relation: str) -> str:
    """Normalize relation labels to uppercase snake case."""

    return "_".join(str(relation).strip().upper().replace("-", "_").split())


def infer_node_type(name: str) -> str:
    """Infer a simple node type for graph metadata and visualization."""

    if name in CANONICAL_COMPANIES:
        return "company"
    if name in CANONICAL_PEOPLE:
        return "person"
    if name in CANONICAL_PRODUCTS:
        return "product"
    if name.isdigit() and len(name) == 4:
        return "year"
    if "," in name or name in {"San Francisco", "London"}:
        return "location"
    return "entity"


def load_raw_triples(path: Path = TRIPLES_PATH) -> list[dict]:
    """Load raw triples generated by `src.extract_triples`."""

    if not path.exists():
        raise FileNotFoundError(f"Raw triples file not found: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def normalize_triples(raw_triples: Iterable[dict]) -> list[NormalizedTriple]:
    """Canonicalize, remove empty values, and deduplicate triples."""

    by_key: dict[tuple[str, str, str], NormalizedTriple] = {}

    for item in raw_triples:
        subject = canonicalize_entity(item.get("subject", ""))
        relation = canonicalize_relation(item.get("relation", ""))
        object_ = canonicalize_entity(item.get("object", ""))

        if not subject or not relation or not object_:
            continue

        confidence = float(item.get("confidence", 0.8))
        source_chunk_id = str(item.get("source_chunk_id", "unknown"))
        key = (subject.casefold(), relation, object_.casefold())
        candidate = NormalizedTriple(
            subject=subject,
            relation=relation,
            object=object_,
            source_chunk_id=source_chunk_id,
            confidence=confidence,
        )

        # Keep the highest-confidence duplicate while preserving a source chunk.
        existing = by_key.get(key)
        if existing is None or candidate.confidence > existing.confidence:
            by_key[key] = candidate

    return sorted(by_key.values(), key=lambda t: (t.subject, t.relation, t.object))


def save_normalized_triples(
    triples: list[NormalizedTriple],
    path: Path = NORMALIZED_TRIPLES_PATH,
) -> None:
    """Persist normalized triples to JSON."""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps([asdict(triple) for triple in triples], indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def load_normalized_triples(path: Path = NORMALIZED_TRIPLES_PATH) -> list[NormalizedTriple]:
    """Load normalized triples from disk."""

    records = json.loads(path.read_text(encoding="utf-8"))
    return [NormalizedTriple(**record) for record in records]


def build_graph(triples: Iterable[NormalizedTriple]) -> nx.MultiDiGraph:
    """Build a directed multi-edge graph from normalized triples."""

    graph = nx.MultiDiGraph()

    for triple in triples:
        for node_name in (triple.subject, triple.object):
            if node_name not in graph:
                graph.add_node(
                    node_name,
                    name=node_name,
                    type=infer_node_type(node_name),
                )

        graph.add_edge(
            triple.subject,
            triple.object,
            relation=triple.relation,
            source_chunk_id=triple.source_chunk_id,
            confidence=triple.confidence,
        )

    return graph


def graph_summary(graph: nx.MultiDiGraph) -> dict[str, object]:
    """Return a compact summary for CLI output and lab notes."""

    type_counts: dict[str, int] = defaultdict(int)
    relation_counts: dict[str, int] = defaultdict(int)

    for _, data in graph.nodes(data=True):
        type_counts[data.get("type", "entity")] += 1

    for _, _, data in graph.edges(data=True):
        relation_counts[data.get("relation", "UNKNOWN")] += 1

    return {
        "num_nodes": graph.number_of_nodes(),
        "num_edges": graph.number_of_edges(),
        "node_type_counts": dict(sorted(type_counts.items())),
        "relation_counts": dict(sorted(relation_counts.items())),
    }


def update_cost_report_normalized_count(
    count: int,
    path: Path = COST_REPORT_PATH,
) -> None:
    """Add the normalized triple count to the existing extraction report."""

    if not path.exists():
        return

    report = json.loads(path.read_text(encoding="utf-8"))
    report["num_normalized_triples"] = count
    path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")


def run_normalization() -> None:
    """Normalize raw triples, save them, and print a graph summary."""

    raw_triples = load_raw_triples()
    normalized_triples = normalize_triples(raw_triples)
    save_normalized_triples(normalized_triples)
    update_cost_report_normalized_count(len(normalized_triples))
    graph = build_graph(normalized_triples)

    print(f"Loaded {len(raw_triples)} raw triples")
    print(f"Saved {len(normalized_triples)} normalized triples to data/processed/normalized_triples.json")
    print(json.dumps(graph_summary(graph), indent=2, ensure_ascii=False))


def parse_args() -> argparse.Namespace:
    return argparse.ArgumentParser(
        description="Normalize raw triples and build a NetworkX graph summary."
    ).parse_args()


if __name__ == "__main__":
    parse_args()
    run_normalization()
